alias glue='sudo docker exec -it glue bash'
alias glue-spark-shell='sudo docker exec -it glue /home/glue_user/spark/bin/spark-shell'
alias glue-spark-submit='sudo docker exec -it glue /home/glue_user/spark/bin/spark-submit'
alias gluepyspark='sudo docker exec -it glue /home/glue_user/spark/bin/pyspark'
alias gluepytest='sudo docker exec -it glue /home/glue_user/.local/bin/pytest'
